syntax = "proto3";
package putm_can;


// PC_TEMPERATURE_CAN_ID = 0x60
message PcTemperatureData {
    uint32 rear_right_inverter_temperature = 1; // [°C], skalowanie: 1x
    uint32 rear_left_inverter_temperature = 2;
    uint32 rear_right_motor_temperature = 3;
    uint32 rear_left_motor_temperature = 4;
    // Dalsze pola z PM09_CANBUS_PC.hpp
}

//PC_MAIN_CAN_ID = 0x10
message PcMainData {
    uint32 vehicle_speed = 1;                  // [km/h], skalowanie: 10x
    uint32 torque_current = 2;                 // [A], skalowanie: 10x
    bool inverters_ready = 3;
    bool rtd = 4;
    uint32 inverter_statuses = 5; // Bitfield: 12 bitów dla status/error/warning
}

//DATA_LOGGER_CAN_ID = 0x57
message DataLoggerStatus {
    uint32 status_flags = 1; // 4 bity: current, voltage, logging, ready
    uint32 msg_cnt = 2;
    uint32 current = 3;      // [mA]
    uint32 voltage = 4;      // [mV]
}