#include "can_interface.hpp"
#include "can_hal.hpp"
#include "generated/can_definitions.pb.h" // Generated by protoc

namespace PUTM_CAN {

/**
 * @brief Structure storing CAN message metadata, including ID and Protobuf data.
 * 
 * This structure can be automatically generated using a script to map CAN IDs to Protobuf types.
 * @note In practice, it is recommended to use a generator to create this mapping automatically.
 */
struct CanMessageMetadata {
    uint32_t id;                        /**< CAN message ID (11-bit or 29-bit). */
    putm_can::PcMainData pc_main_data;  /**< Example Protobuf data buffer in CanInterface. */
};

/**
 * @brief Constructor for CanInterface.
 * 
 * Initializes the HAL and sets up message buffers if needed.
 * @param hal_ptr Pointer to the ICanHal implementation.
 */
CanInterface::CanInterface(ICanHal* hal_ptr) : hal(hal_ptr) {
    // Initialize HAL
    if (hal) {
        hal->init();
    } else {
        // Error: No HAL pointer (logging could be added in real code)
    }
    // Initialize message buffers if needed
}

/**
 * @brief Handles incoming CAN messages.
 * 
 * Receives CAN frames from the hardware and deserializes them into appropriate Protobuf types,
 * triggering actions based on the ID.
 */
void CanInterface::handle_incoming_messages() {
    CanFrame frame;
    // Receive all available frames
    while (hal->receive(frame)) {
        switch (frame.id) {
            case 0x60: // PC_TEMPERATURE_CAN_ID
                /**
                 * @brief Deserializes PC temperature message.
                 * 
                 * Checks data size to avoid overflow and updates temperature data.
                 */
                if (frame.dlc <= frame.data.size()) {
                    current_pc_temp_data.ParseFromArray(frame.data.data(), frame.dlc);
                    pc_temperature_new_data = true;
                }
                break;
            // ... other cases for 0x10, 0x57, etc.
            default:
                // Unknown ID
                break;
        }
    }
}

/**
 * @brief Template method to send a CAN message.
 * 
 * Serializes a Protobuf object into a CAN frame and transmits it via hardware.
 * @tparam T The Protobuf message type (e.g., PcMainData).
 * @param msg Reference to the Protobuf message to send.
 * @param can_id The CAN message ID.
 * @return true if the send operation succeeded, false otherwise.
 */
template <typename T>
bool CanInterface::send_message(const T& msg, uint32_t can_id) {
    CanFrame frame;
    frame.id = can_id;

    // 1. Serialize Protobuf to a static buffer
    std::array<uint8_t, 8> buffer{}; // Static buffer sized for CAN frame
    if (!msg.SerializeToArray(buffer.data(), buffer.size())) {
        return false; // Serialization error
    }

    // 2. Copy to CAN frame (already sized appropriately)
    frame.dlc = std::min(static_cast<size_t>(msg.ByteSizeLong()), buffer.size()); // Use actual size or max 8
    std::copy(buffer.begin(), buffer.begin() + frame.dlc, frame.data.begin());

    // 3. Transmit
    return hal->transmit(frame);
}

/**
 * @brief Sends PC main data via CAN.
 * 
 * Uses the template send_message method for PcMainData with ID 0x10.
 * @param msg The PcMainData object to send.
 * @return true if the send operation succeeded, false otherwise.
 */
bool CanInterface::send_pc_main_data(const putm_can::PcMainData& msg) {
    return send_message(msg, 0x10); // PC_MAIN_CAN_ID
}

} // namespace PUTM_CAN