/**
 * @file dbc_registry.cpp
 * @brief Manual implementation of the DBC Registry.
 * @details In the future, this file content should be generated by the Python script.
 */

#include "message_handler.hpp" // Definicja struct DbcEntry
#include "PUTM_CAN_M.h" // Wygenerowane makra i funkcje C

namespace putm_ev_can {

//  Szablon "Thunk" rzutujący funkcje C na sygnaturę wymaganą przez bibliotekę (void*)
template<typename MsgT,
         int(*Pack)(uint8_t*, const MsgT*, size_t),
         int(*Unpack)(MsgT*, const uint8_t*, size_t)>
struct DbcThunk {
    static int pack_generic(uint8_t* d, const void* s, size_t n) {
        return Pack(d, reinterpret_cast<const MsgT*>(s), n);
    }
    static int unpack_generic(void* d, const uint8_t* s, size_t n) {
        return Unpack(reinterpret_cast<MsgT*>(d), s, n);
    }
};

// Makro pomocnicze do wypełniania tablicy
#define DBC_ENTRY(MSG_UP, msg_lc) \
    { PUTM_CAN_M_##MSG_UP##_FRAME_ID, \
      PUTM_CAN_M_##MSG_UP##_LENGTH, \
      (void*)&DbcThunk<PUTM_CAN_M_##msg_lc##_t, \
                PUTM_CAN_M_##msg_lc##_pack, \
                PUTM_CAN_M_##msg_lc##_unpack>::pack_generic, \
      (void*)&DbcThunk<PUTM_CAN_M_##msg_lc##_t, \
                PUTM_CAN_M_##msg_lc##_pack, \
                PUTM_CAN_M_##msg_lc##_unpack>::unpack_generic }

// ==================================================================================
// REJESTR WIADOMOŚCI
// Tutaj wypełniamy wszystkie wiadomości z DBC, których używamy
// ==================================================================================
static const DbcEntry DBC_REGISTRY[] = {
    DBC_ENTRY(REARBOX_SAFETY,          rearbox_safety),
    DBC_ENTRY(REARBOX_TEMPERATURE,     rearbox_temperature),
    DBC_ENTRY(REARBOX_MISCELLANEOUS,   rearbox_miscellaneous),
    DBC_ENTRY(PC_TEMPERATURE_DATA,     pc_temperature_data),
    DBC_ENTRY(PC_MAIN_DATA,            pc_main_data),
    DBC_ENTRY(PC_LAP_TIMER_DATA,       pc_lap_timer_data),
    DBC_ENTRY(PDU_CHANNNEL,            pdu_channnel),
    DBC_ENTRY(PDU_DATA,                pdu_data),
    DBC_ENTRY(DRIVER_INPUT,            driver_input),
    DBC_ENTRY(FRONT_DATA,              front_data),
    DBC_ENTRY(DASHBOARD,               dashboard),
    DBC_ENTRY(BMS_LV_MAIN,             bms_lv_main),
    DBC_ENTRY(BMS_LV_TEMPERATURE,      bms_lv_temperature),
    DBC_ENTRY(BMS_HV_MAIN,             bms_hv_main)
};


const DbcEntry* find_dbc_entry(PUTM_CAN::CanId id) {
    for (const auto& e : DBC_REGISTRY) {
        if (e.id == id) return &e;
    }
    return nullptr;
}

} // namespace putm_ev_can